### ISSUE TITLE
Text-Generation-Inference Docker container not working with quantize parameter

### ISSUE THREAD

**Issue by solarslurpi** [runpod/runpod-python#90] opened 2023-08-11 21:37 UTC
When spinning up the docker container with this code that uses the TGI docker image:
```
    pod = runpod.create_pod(
        name="tiiuae/falcon-7b-instruct",
        image_name="ghcr.io/huggingface/text-generation-inference:1.0.0",
        gpu_type_id="NVIDIA GeForce RTX 3090",
        cloud_type="COMMUNITY",
        docker_args=docker_args, # SEE BELOW
        gpu_count=1,
        volume_in_gb=30,
        container_disk_in_gb=5,
        ports="80/http",
        volume_mount_path="/data",
    )
```
**if `docker_args` includes the quantize property, (quantize is True)** e.g.:
    docker_args = "--model-id tiiuae/falcon-7b-instruct--num-shard 1 "

    if quantize:
        docker_args += " --quantize bitsandbytes"

**The container log spits out:**
```
2023-08-10T11:30:29.101220272-06:00 /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable. 
```
**From HF support (Nicolas Patry)**: "This means for whatever reason the pod you're using cannot see the GPU. There are issues opened for that directly at runpod if I'm not mistakened. But we've seen people having issues with runpod before.  **Something about shm not being properly set or something."**

From Nicolas/HF perspective, the bug is in how the pod is set up.  He believes it has to do with not properly setting up shared memory?

**To Reproduce**
- spin up a pod with the above `create_pod` settings and `docker_args` set to 
  `docker_args = "--model-id tiiuae/falcon-7b-instruct --num-shard 1 --quantize bitsandbytes"`

if you spin up without --quantize:
`docker_args = "--model-id tiiuae/falcon-7b-instruct --num-shard 1` 

the container will load correctly.  Yet, the feature that minimizes the amount of memory which will minimize the cost and inference time are not being used.  

**Expected behavior**
The container will use less memory and the inference times will be shorter.

Thank you.

**Comment by chris-aeviator** [comment] 2023-08-27 09:42
I was unable to reproduce your issue using SECURE cloud and Llama 2 - I can get TGI (lastest) to work with quantization=bitsandbytes

❯ curl https://xxxxxxxxxxx-80.proxy.runpod.net/generate \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":200}}' \
    -H 'Content-Type: application/json'
{"generated_text":"\nWhat is Deep Learning? Deep learning is a subset of machine learning that is based on artificial neural networks. Neural networks are algorithms that are inspired by the structure and function of the human brain. Deep learning is a subset of machine learning that is based on artificial neural networks. Neural networks are algorithms that are inspired by the structure and function of the human brain.\nDeep learning is a subset of machine learning that is based on artificial neural networks. Neural networks are algorithms that are inspired by the structure and function of the human brain. Deep learning is a subset of machine learning that is based on artificial neural networks. Neural networks are algorithms that are inspired by the structure and function of the human brain.\nDeep learning is a subset of machine learning that is based on artificial neural networks. Neural networks are algorithms that are inspired by the structure and function of the human brain. Deep learning is a subset of machine learning that is based on artificial neural networks. Neural networks are"}%

**Comment by justinmerrell** [comment] 2023-08-27 21:24
Thank you for the input @chris-aeviator 

@solarslurpi I am not sure this is the best location for this issue unless you think there is a fix within this repo that would resolve things for you.

**Comment by justinmerrell** [comment] 2023-08-28 13:31
Closing for now, not related to this repo.

**Closed by justinmerrell** 2023-08-28 13:31 UTC
Labels: bug
